---
title: Physical Computing With Scratch
hero_image: images/banner.png
description: A guide to getting started with physical computing and Scratch
original_url: https://raspberrypi.org/learning/physical-computing-with-scratch
theme: orange
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-2, manufacture-0, community-0
interests: ''
technologies: electronic-components, scratch
site_areas: projects
hardware: electronic-components
software: scratch
version: 3
last_tested: 2019-08-19
steps:
- title: Introduction
  completion: engaged
- title: Lighting an LED
- title: Using a switchable pin
  completion: engaged
- title: Connecting a button
- title: Buzzers
  completion: internal
- title: Passive infrared motion sensor (PIR)
  completion: internal
- title: 'Challenge: Make a burglar alarm'
  challenge: true
- title: What next?
